from streetlight import Streetlight
from common_test import OrionRequestData, KafkaMenssage
from wasteContainer import WasteContainer

alcobendas_streelight_streelight = OrionRequestData(
    name="alcobendas_streelight_streelight",
    service="alcobendas",
    subservice="/streelight",
    entities= Streetlight["entities"],
    subscriptions={"historic":Streetlight["subscriptions"]["historic"]},
    updateEntities= Streetlight["updateEntities"]
)

alcobendas_dumps_wastecontainer = OrionRequestData(
    name="alcobendas_dumps_wasteconaster",
    service="alcobendas",
    subservice="/dumps",
    entities= WasteContainer["entities"],
    subscriptions={"historic":WasteContainer["subscriptions"]["historic"]},
    updateEntities= WasteContainer["updateEntities"],
)

jcyl_dumps_wastecontainer = OrionRequestData(
    name="jcyl_dumps_wasteconaster",
    service="jcyl",
    subservice="/dumps",
    entities= WasteContainer["entities"],
    subscriptions={"historic":WasteContainer["subscriptions"]["historic"]},
    updateEntities= WasteContainer["updateEntities"],
)

entry_one_entity: list[OrionRequestData] = [alcobendas_streelight_streelight]
expected_one_entity = [
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:15:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350063, 40.054448]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 9. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.5, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': True, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '20 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['high-efficiency', 'dynamic-color'], 'sensors': {'motion': True, 'ambient_light': False}, 'zigbee_channel': 25}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': '@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 15, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483647, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203685, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1989.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4000.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 30.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 6.5e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10001, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Gamma', 'STL-Omega', 'STL-Nova'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [10, 25, 50, 75, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [2700, 3000, 4000, 5000, 6500], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:20:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350163, 40.054548]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 10. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.6, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': False, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '21 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['high-efficiency', 'dynamic-color', 'eco-mode'], 'sensors': {'motion': False, 'ambient_light': True}, 'zigbee_channel': 26}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'soporte_tecnico@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 16, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483648, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203686, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1990.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4100.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 31.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 6.6e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10002, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Gamma', 'STL-Omega', 'STL-Nova', 'STL-Quantum'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [15, 30, 55, 80, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [2750, 3100, 4100, 5100, 6600], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:25:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350263, 40.054648]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 11. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.7, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': True, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '22 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['high-efficiency'], 'sensors': {'motion': True, 'ambient_light': False}, 'zigbee_channel': 27}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'asistencia@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 17, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483649, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203687, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1991.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4200.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 32.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 6.7e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10003, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Gamma', 'STL-Omega'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [20, 35, 60, 85, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [2800, 3200, 4200, 5200, 6700], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:30:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350363, 40.054748]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 12. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.8, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': False, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '23 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['dynamic-color'], 'sensors': {'motion': False, 'ambient_light': True}, 'zigbee_channel': 28}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'soporte@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 18, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483650, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203688, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1992.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4300.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 33.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 6.8e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10004, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Nova', 'STL-Quantum'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [25, 40, 65, 90, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [2850, 3300, 4300, 5300, 6800], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:35:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350463, 40.054848]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 13. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.9, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': True, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '24 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['high-efficiency', 'eco-mode'], 'sensors': {'motion': True, 'ambient_light': True}, 'zigbee_channel': 29}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'tecnico@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 19, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483651, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203689, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1993.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4400.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 34.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 6.9e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10005, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Omega', 'STL-Nova'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [30, 45, 70, 95, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [2900, 3400, 4400, 5400, 6900], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:40:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350563, 40.054948]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 14. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 1, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': False, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '25 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['dynamic-color', 'eco-mode'], 'sensors': {'motion': False, 'ambient_light': False}, 'zigbee_channel': 30}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'asistencia_tecnica@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 20, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483652, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203690, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1994.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4500.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 35.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 6.999999999999999e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10006, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Gamma', 'STL-Quantum'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [35, 50, 75, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [2950, 3500, 4500, 5500, 7000], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:45:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350663, 40.055048]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 15. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.4, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': True, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '26 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['high-efficiency'], 'sensors': {'motion': True, 'ambient_light': True}, 'zigbee_channel': 31}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'soporte_luminica@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 21, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483653, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203691, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1995.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4600.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 36.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 7.1e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10007, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Omega', 'STL-Quantum'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [40, 55, 80, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [3000, 3600, 4600, 5600, 7100], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:50:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350763, 40.055148]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 16. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.3, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': False, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '27 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['dynamic-color'], 'sensors': {'motion': False, 'ambient_light': False}, 'zigbee_channel': 32}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'mantenimiento@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 22, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483654, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203692, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1996.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4700.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 37.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 7.2e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10008, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Nova'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [45, 60, 85, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [3050, 3700, 4700, 5700, 7200], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T05:55:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350863, 40.055248]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 17. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.2, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': True, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '28 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['eco-mode'], 'sensors': {'motion': True, 'ambient_light': False}, 'zigbee_channel': 33}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'soporte_iluminacion@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 23, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483655, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203693, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1997.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4800.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 38.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 7.3e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10009, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Gamma', 'STL-Omega', 'STL-Nova', 'STL-Quantum', 'STL-Alpha'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [50, 65, 90, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [3100, 3800, 4800, 5800, 7300], 'metadata': {}}}]}),
    KafkaMenssage(headers={'fiware-service': 'alcobendas', 'fiware-servicepath': 'streelight'}, menssage={'data': [{'id': 'ENT-LUM-001', 'type': 'Streetlight', 'TimeInstant': {'type': 'DateTime', 'value': '2025-01-01T06:00:00.000Z', 'metadata': {}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [-0.350963, 40.055348]}, 'metadata': {}}, 'address': {'type': 'Text', 'value': 'Calle Honorato Ros, 18. 12230 Argelita, Castell�n', 'metadata': {}}, 'illuminanceLevel': {'type': 'Number', 'value': 0.1, 'metadata': {}}, 'enableHistoricCommand': {'type': 'Boolean', 'value': False, 'metadata': {}}, 'variables': {'type': 'jsonb', 'value': {'duration': '29 days'}, 'metadata': {}}, 'fixtureConfiguration': {'type': 'json', 'value': {'modes': ['high-efficiency', 'dynamic-color', 'eco-mode'], 'sensors': {'motion': False, 'ambient_light': True}, 'zigbee_channel': 34}, 'metadata': {}}, 'maintainerEmail': {'type': 'TextUnrestricted', 'value': 'ayuda@telefonica.com', 'metadata': {}}, 'lumensAdjustment': {'type': 'Number', 'value': 24, 'metadata': {}}, 'fixtureModelId': {'type': 'Number', 'value': 2147483656, 'metadata': {}}, 'ledCount': {'type': 'Number', 'value': 922337203694, 'metadata': {}}, 'wattageConsumption': {'type': 'Number', 'value': 1998.0, 'metadata': {}}, 'colorTempKelvin': {'type': 'Number', 'value': 4900.1234, 'metadata': {}}, 'beamAngle': {'type': 'Number', 'value': 39.75, 'metadata': {}}, 'luminousEfficacy': {'type': 'Number', 'value': 7.4e+39, 'metadata': {}}, 'installationId': {'type': 'Number', 'value': 10010, 'metadata': {}}, 'compatibleFixtures': {'type': 'json', 'value': ['STL-Quantum'], 'metadata': {}}, 'dimmingLevels': {'type': 'json', 'value': [55, 70, 95, 100], 'metadata': {}}, 'temperatureRangeK': {'type': 'json', 'value': [3150, 3900, 4900, 5900, 7400], 'metadata': {}}}]})
]

entry_two_different_entities_subservices = [alcobendas_streelight_streelight, alcobendas_dumps_wastecontainer]
expected_two_different_entities_subservices = []

entry_two_different_service_and_subservice_entities  = [alcobendas_streelight_streelight, alcobendas_dumps_wastecontainer],
expected_two_different_service_and_subservice_entities = []

sink_historic = [
    (
        entry_one_entity,
        expected_one_entity
    ),
    (
        entry_two_different_entities_subservices,
        expected_two_different_entities_subservices
    ),
    (
        entry_two_different_service_and_subservice_entities,
        expected_two_different_service_and_subservice_entities
    )
]

