sonar.projectKey=telefonicaid_kafnus_74ccf87d-1b34-4077-bcd4-92934aff97f8
sonar.projectName=kafnus
sonar.host.url=https://sonarqube-colab.iotplatform.telefonica.com
sonar.sourceEncoding=UTF-8

sonar.sources=kafnus-ngsi
sonar.tests=kafnus-ngsi/tests

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/old/**,\
  **/*.json, \
  kafnus-ngsi/tests/**

sonar.javascript.lcov.reportPaths=kafnus-ngsi/coverage/lcov.info
