# Copyright 2026 Telefónica Soluciones de Informática y Comunicaciones de España, S.A.U.
#
# This file is part of kafnus
#
# kafnus is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# kafnus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with kafnus. If not, see http://www.gnu.org/licenses/.

name: Kafnus NGSI Coverage

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'kafnus-ngsi/**'
      - '.github/workflows/kafnus_ngsi_coverage.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'kafnus-ngsi/**'
      - '.github/workflows/kafnus_ngsi_coverage.yml'

jobs:
  unit-tests-coverage:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: kafnus-ngsi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests with coverage
        run: npm test -- --coverageReporters=text-summary --coverageReporters=lcov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: kafnus-ngsi/coverage/lcov.info
          flag-name: kafnus-ngsi